# Generated by Django 3.2 on 2022-09-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('number', models.CharField(max_length=10)),
                ('response', models.TextField()),
                ('status_message', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('otp_number', models.CharField(max_length=6)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': "SMS's",
            },
        ),
    ]
