# Generated by Django 3.2 on 2022-09-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
