# Generated by Django 3.2 on 2022-09-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_sms_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
