# Generated by Django 3.2 on 2022-09-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_sms_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sms',
            options={'default_permissions': (), 'permissions': (('access_service', 'Can Access Service Page'), ('edit_service', 'Can Edit service')), 'verbose_name': 'SMS', 'verbose_name_plural': "SMS's"},
        ),
    ]
