# Generated by Django 3.2 on 2022-09-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_sms_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sms',
            options={'verbose_name': 'SMS', 'verbose_name_plural': "SMS's"},
        ),
    ]
